ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/workflows/*
          - .github/labeler.yml

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - Cargo.toml
          - Cargo.lock

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - README.md
          - RELEASE.md
          - CHANGELOG.md
          - CODE_OF_CONDUCT.md

github_actions:
  - changed-files:
      - any-glob-to-any-file:
          - .github/workflows/*
          - .github/labeler.yml

rust:
  - changed-files:
      - any-glob-to-any-file:
          - src/*
          - examples/*
          - benches/*
