[package]
name = "logged-stream"
version = "0.2.1"
edition = "2021"
authors = ["Alexandr Garbuzov <qwerty541zxc@gmail.com>"]
description = "This Rust library provides a wrapper for io objects like `std::net::TcpStream` to enable logging of all read and write operations, errors and drop."
keywords = ["io", "logging", "async", "network"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/qwerty541/logged-stream"
homepage = "https://github.com/qwerty541/logged-stream"
documentation = "https://docs.rs/logged-stream"
readme = "./README.md"
rust-version = "1.60.0"
exclude = [".github", ".vscode", "examples", ".gitignore", "rustfmt.toml"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
chrono = "0.4.24"
itertools = "0.10.5"
log = "0.4.17"
tokio = { version = "1.27.0", features = ["io-util"], default-features = false }

[dev-dependencies]
env_logger = "0.10.0"
tokio = { version = "1.27.0", features = [
    "macros",
    "net",
    "rt-multi-thread"
], default-features = false }
