[package]
name = "logged-stream"
version = "0.1.0"
edition = "2021"
authors = ["Alexandr Garbuzov <qwerty541zxc@gmail.com>"]
description = """
This Rust library provides a wrapper for structures which implements `std::io::Read` and `std::io::Write` traits or their asynchronous analogues
from tokio to enable logging of all read and write operations, errors and drop. Simple example of usage: logging traffic of TCP stream into console. 
"""
keywords = ["io", "logging"]
license = "MIT or Apache-2.0"
repository = "https://github.com/qwerty541/logged-stream"
documentation = "https://docs.rs/logged-stream"
readme = "./README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
chrono = "0.4.24"
log = "0.4.17"
tokio = { version = "1.27.0", features = ["io-util"], default-features = false }

[dev-dependencies]
env_logger = "0.10.0"
tokio = { version = "1.27.0", features = [
    "macros",
    "net",
    "rt-multi-thread"
], default-features = false }
