name: labeler

on:
  - pull_request_target

permissions:
  actions: none
  artifact-metadata: none
  attestations: none
  checks: none
  contents: read
  deployments: none
  discussions: none
  id-token: none
  issues: none
  models: none
  packages: none
  pages: none
  pull-requests: write
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  triage:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
