name: labeler

on:
  - pull_request_target

permissions:
  actions: none
  artifact-metadata: none
  attestations: none
  checks: none
  contents: read
  deployments: none
  discussions: none
  id-token: none
  issues: none
  models: none
  packages: none
  pages: none
  pull-requests: write
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  triage:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Triage
        uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13 # v7.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
